name: Testing and coverage report

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    util-testing:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Use pnpm
              run: |
                  npm install -g pnpm
                  pnpm install

            - name: util test
              run: pnpm test

            - name: testing coverage
              run: pnpm test:coverage
